<?php

/**
 * @file User node invite module file.
 */

/**
 * Implements hook_help().
 */
function user_node_invite_help($path, $arg) {
  switch ($path) {
    case 'admin/help#user_node_invite':
      $output = 'Insert help text';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function user_node_invite_menu() {
  $items = array();

  $items['node/%node/user-node-invite'] = array(
    'title' => 'Invite users',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_node_invite_page', 1), //refers to: function user_node_invite_page($form, &$form_state, $node)
    'access callback' => 'user_node_invite_page_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function user_node_invite_permission() {
  return array(
    'grant user node invite' => array(
      'title' => t('Invite users to nodes'),
      'description' => t('Invite users for any nodes'),
    ),
    'grant user own node invite' => array(
      'title' => t('Invite users to own nodes'),
      'description' => t('Invite users for own nodes'),
    ),
  );
}

/**
 * Get access tab page for the viewed node.
 */
 function user_node_invite_page_access($node) {
  global $user;
  return user_access('grant user node invite') ||
         (user_access('grant user own node invite') && ($user->uid == $node->uid));
}

function user_node_invite_page($form, &$form_state, $node){
	$form['first_name'] = array(
	'#type' => 'textfield',
	'#title' => t('First Name'),
	'#required' => TRUE,);
	
	$form['last_name'] = array(
	'#type' => 'textfield',
	'#title' => t('Last Name'),
	'#required' => TRUE,);
	
	$form['email'] = array(
	'#type' => 'textfield',
	'#title' => t('E-Mail'),
	'#required' => TRUE,);
	
	$form['send_email'] = array(
	'#type' => 'checkbox',
	'#title' => t('Send invitation notification'));
	
	$form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create Invitation'),
    '#weight' => 10,
  );
  
  return $form;
}

function user_node_invite_page_submit($form, &$form_state) {
	dpr($form_state);
	$user_data = $form_state['values'];
	
	// Fetch uid of the user if a user with the provided email already exists in the database
	$existing_user = user_load_by_mail($user_data['email']);
	if(is_object($existing_user))
		$uid = $existing_user->uid;

	// If the user did not already exist, create him/her
	if(!isset($uid)) {
		$account = array();
		$account['mail'] = $user_data['email'];
		$account['init'] = $user_data['email'];
		$account['status'] = 1;
  
		// Derive the username from the email
		$username = preg_replace('/@.*$/', '', $user_data['email']);
		$account['name'] = user_node_invite_unique_username($username);
	  
		// Generate a random password
		$account['pass'] = user_password();
	  
		$account = array_merge($account, user_node_invite_assign_core_fields($user_data));
		$account = user_save('', $account);
			
		// Retrieve User ID
		$uid = (array)$account;
		$uid = $uid['uid'];
		
		$existing_user_notification = "";
	} else {
		$existing_user_notification = t("However, a user with the provided email was already present in the database and could be reused. ");
		$account = user_load_by_mail($user_data['email']);
	}
	
	// Retrieve Node ID
		if($node=menu_get_object())
			$nid = $node->nid;
	
	// Retrieve ACL ID or create a new ACL if necessary
	$acl_id = acl_get_id_by_name("content_access", "update_" . $nid);

	if($acl_id == null)
		$acl_id = acl_create_acl("content_access", "update_" . $nid);	
	
	// Add user to ACL
	acl_add_user($acl_id, $uid);
	
	// Add node to ACL, if not already done
	acl_node_add_acl($nid, $acl_id, 0, 1, 0);
	
	// Switch authorization mode of node to acl, if this was not already done before
	$permissionset = db_query('SELECT * FROM node_access WHERE nid = :nid AND realm = :acl', array(':nid' => $nid, ':acl' => "acl"));
	$rights_missing = true;
	foreach($permissionset as $permission) {
		if(isset($permission))
			$rights_missing = false;
	}
	
	if($rights_missing) {
		$access_entry = new stdClass;
		$access_entry->nid = $nid;
		$access_entry->gid = $acl_id;
		$access_entry->realm = "acl";
		$access_entry->grant_view = 0;
		$access_entry->grant_update = 1;
		$access_entry->grant_delete = 0;
		drupal_write_record("node_access", $access_entry);
	}

	// Retrieve the token for the created user from the database
	$token_query = db_query('SELECT token FROM tokenauth_tokens WHERE uid = :uid', array(':uid' => $uid));
	foreach($token_query as $entry) {
		$token = $entry->token;
	}
	
	// Generate the tokenized path to the current node using the created user
	$tokenized_path = url('node/' . $nid, array('absolute' => TRUE, 'query' => array('token' => $token)));
	
	// Sends an invitation email to the user if the option was checked in the form	
	if($user_data['send_email']) {
		$params['account'] = $account;
		$params['tokenized_path'] = $tokenized_path;
		drupal_mail('user_node_invite', 'node_invite_created', $account->mail, user_preferred_language($account), $params);
		$email_notification = t("The invitation was successfully created and the user was notified via E-mail. You find a copy of the link which was sent to the user below. ");
	} else
		$email_notification = t("The invitation was successfully created, but the user was not notified. You find the link, which the user should receive, below. ");

	
	drupal_set_message($email_notification . $existing_user_notification . t('The invitation link for @mail is: @link', array('@mail' => $user_data['email'], '@link' => $tokenized_path)));
	return $account;
}

function user_node_invite_unique_username($name, $uid = 0) {
  // Strip illegal characters
  $name = preg_replace('/[^\x{80}-\x{F7} a-zA-Z0-9@_.\'-]/', '', $name);

  // Strip leading and trailing whitespace
  $name = trim($name);

  // Convert any other series of spaces to a single space
  $name = preg_replace('/ +/', ' ', $name);

  // If there's nothing left use a default
  $name = ('' === $name) ? t('user') : $name;

  // Truncate to reasonable size
  $name = (drupal_strlen($name) > (USERNAME_MAX_LENGTH - 10)) ? drupal_substr($name, 0, USERNAME_MAX_LENGTH - 11) : $name;

  // Iterate until we find a unique name
  $i = 0;
  do {
    $newname = empty($i) ? $name : $name . '_' . $i;
    $args = array(':uid' => $uid, ':name' => $newname);
    $found = db_query_range('SELECT uid from {users} WHERE uid <> :uid AND name = :name', 0, 1, $args)->fetchField();
    $i++;
  } while ($found);

  return $newname;
}

function user_node_invite_assign_core_fields($user_data) {
  $fields = array();
  
  // see http://hojtsy.hu/blog/2011-jan-31/drupal-7039s-new-multilingual-systems-part-4-node-translation
  $fields['field_profile_firstname'][LANGUAGE_NONE][0]['value'] = $user_data['first_name'];
  $fields['field_profile_name'][LANGUAGE_NONE][0]['value'] = $user_data['last_name'];
  
  return $fields;
}

function user_node_invite_form_alter(&$form, &$form_state, $form_id) {
	if($form_id == 'project_node_form' || $form_id == 'organization_node_form') {
		unset($form['#token']);
	}
}

function user_node_invite_mail($key, &$message, $params) {
    $data['user'] = $params['account'];
    $options['language'] = $message['language'];
    user_mail_tokens($variables, $data, $options);
    switch($key) {
      case 'node_invite_created':
        $langcode = $message['language']->language;
        $message['subject'] = t('Contribution invititation from tech4p', $variables, array('langcode' => $langcode));
        $message['body'][] = t("Dear Sir or Madam\n\nYou have been invited to contribute to the Tech4p research-portal.\nYour input is required on specific content, which can be found under the following link:\n@link\n\nKind regards,\nTech4p Research Portal", array('@link' => $params['tokenized_path']), array('langcode' => $langcode));
        break;
    }
  }