<?php

/**
 * @file User node invite module file.
 */

/**
 * Implements hook_help().
 */
function user_node_invite_help($path, $arg) {
  switch ($path) {
    case 'admin/help#user_node_invite':
      $output = 'Insert help text';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function user_node_invite_menu() {
  $items = array();

  $items['node/%node/user-node-invite'] = array(
    'title' => 'Invite users',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_node_invite_page', 1), //refers to: function user_node_invite_page($form, &$form_state, $node)
    //'access callback' => 'content_access_node_page_access',
    'access callback' => TRUE,
    //'access arguments' => array(1),
    //'file' => 'content_access.admin.inc',
    //'theme callback' => '_node_custom_theme',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function user_node_invite_permission() {
  return array(
    'grant user node invite' => array(
      'title' => t('Invite users to nodes'),
      'description' => t('Invite users for any nodes'),
    ),
    'grant user own node invite' => array(
      'title' => t('Invite users to own nodes'),
      'description' => t('Invite users for own nodes'),
    ),
  );
}

/**
 * Get access tab page for the viewed node.
 */
 /* function content_access_node_page_access($node) {
  global $user;
  return content_access_get_settings('per_node', $node->type) && user_access('grant content access') ||
    content_access_get_settings('per_node', $node->type) && (user_access('grant own content access') && ($user->uid == $node->uid));
} */

function user_node_invite_page($form, &$form_state, $node){
  $form['name'] = array(
    '#type' => 'textfield',
	'#title' => t('Name'),
	'#required' => FALSE,);
	
  $form['email'] = array(
    '#type' => 'textfield',
	'#title' => t('E-Mail'),
	'#required' => TRUE,);
	
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create Invitation'),
    '#weight' => 10,
  );
  
  return $form;
}

function user_node_invite_page_submit($form, &$form_state) {
	dpr($form_state);
	
	//The logic is done here...
}